[package]
name = "libraw-sys"
version = "0.1.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]

build = "build.rs"
links = "raw"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3.2"
